<?php
if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly.
}

class QP_Backup_Restore_Page
{
    /**
     * Renders the Backup & Restore tab content.
     */
    public static function render()
    {
        // In future steps, we will add logic here to fetch local backups.
        $local_backups = []; // Placeholder for now.
?>
        <div id="col-container" class="wp-clearfix">
            <div id="col-left">
                <div class="col-wrap">
                    <div class="form-wrap">
                        <h2>Create New Backup</h2>
                        <p>Click the button below to generate a full backup of all your Question Press data, including questions, groups, subjects, topics, sources, exams, labels, and associated images.</p>
                        <p>
                            <a href="#" class="button button-primary" id="qp-create-backup-btn">Create New Backup</a>
                        </p>
                    </div>
                    <hr>
                    <div class="form-wrap">
                        <h2>Restore from Backup</h2>
                        <p>Upload a <code>.zip</code> backup file that was generated by this tool to restore your data. <strong>Warning:</strong> This will overwrite any existing data with the contents of the backup file.</p>
                        <form id="qp-restore-form" method="post" enctype="multipart/form-data">
                            <?php wp_nonce_field('qp_restore_nonce_action', 'qp_restore_nonce_field'); ?>
                            <div class="form-field">
                                <label for="backup_zip_file">Backup File (.zip)</label>
                                <input type="file" name="backup_zip_file" id="backup_zip_file" accept=".zip,application/zip" required>
                            </div>
                            <p class="submit">
                                <input type="submit" class="button button-danger" value="Upload and Restore">
                            </p>
                        </form>
                    </div>
                </div>
            </div>
            <div id="col-right">
                <div class="col-wrap">
                    <h3>Local Backups</h3>
                    <table class="wp-list-table widefat fixed striped">
                        <thead>
                            <tr>
                                <th>Backup Date</th>
                                <th>Backup Name</th>
                                <th>File Size</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (empty($local_backups)) : ?>
                                <tr class="no-items">
                                    <td class="colspanchange" colspan="4">No local backups found.</td>
                                </tr>
                            <?php else : ?>
                                <?php // Loop will go here in a future step ?>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
<?php
    }
}